gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - blue
    selectedRangeBgColor:
      - blue
